#!/bin/bash

. $(dirname $0)/../config.sh

if [ -z $1 ] ; then
  etape=osm2pgsql
else
  etape=$1
fi

if [ "$1" == "" ] ; then
  echo "This tool computes timespent by one of those 3 steps : osm2pgsql, osmosis ou tile_expiry"
  echo "usage : ./infos_temps osmosis"
fi

i=0 
tot=0
for x in `grep $etape $work_dir/diff-update-timing | cut -f3 -d,` ; do 
  i=$(($i+1)) 
  tot=$(($tot+$x)) 
done 
echo "Step $etape took on average $(($tot/$i)) seconds"
