-- osm2pgsql allready do that for us
-- drop table planet_osm_line;
--drop table planet_osm_nodes;
--drop table planet_osm_point;
--drop table planet_osm_polygon;
--drop table planet_osm_rels;
--drop table planet_osm_roads;
--drop table planet_osm_ways;
